# Generated by Django 2.2 on 2019-04-02 20:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20190403_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='content',
            field=models.TextField(),
        ),
    ]
