# Generated by Django 2.2 on 2019-04-02 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20190403_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='time',
        ),
    ]
