# Generated by Django 2.2 on 2019-04-03 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_todotime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoTime',
        ),
    ]
